// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFfemPgfgMUoQsOEPyhySQGQkaUIw91s',
    appId: '1:158785144699:web:775e7de8638968edb05fde',
    messagingSenderId: '158785144699',
    projectId: 'uts-true-michu',
    authDomain: 'uts-true-michu.firebaseapp.com',
    databaseURL: 'https://uts-true-michu-default-rtdb.firebaseio.com',
    storageBucket: 'uts-true-michu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgSCImFfw6U4fH6usB-EO6FMeHd2g4jM',
    appId: '1:158785144699:android:2b0fe4720dc0ae58b05fde',
    messagingSenderId: '158785144699',
    projectId: 'uts-true-michu',
    databaseURL: 'https://uts-true-michu-default-rtdb.firebaseio.com',
    storageBucket: 'uts-true-michu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3_bQxFhP9AfOfhU5wi9xQdBeFagjSbc',
    appId: '1:158785144699:ios:45bd3b629797f6e1b05fde',
    messagingSenderId: '158785144699',
    projectId: 'uts-true-michu',
    databaseURL: 'https://uts-true-michu-default-rtdb.firebaseio.com',
    storageBucket: 'uts-true-michu.firebasestorage.app',
    iosBundleId: 'com.example.latUts1true',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu3_bQxFhP9AfOfhU5wi9xQdBeFagjSbc',
    appId: '1:158785144699:ios:45bd3b629797f6e1b05fde',
    messagingSenderId: '158785144699',
    projectId: 'uts-true-michu',
    databaseURL: 'https://uts-true-michu-default-rtdb.firebaseio.com',
    storageBucket: 'uts-true-michu.firebasestorage.app',
    iosBundleId: 'com.example.latUts1true',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBFfemPgfgMUoQsOEPyhySQGQkaUIw91s',
    appId: '1:158785144699:web:6b9866b48c852087b05fde',
    messagingSenderId: '158785144699',
    projectId: 'uts-true-michu',
    authDomain: 'uts-true-michu.firebaseapp.com',
    databaseURL: 'https://uts-true-michu-default-rtdb.firebaseio.com',
    storageBucket: 'uts-true-michu.firebasestorage.app',
  );

}