// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANAzvls5G_xdVx5LPxB7BKqsbjyl78SMA',
    appId: '1:476508855204:web:09fb54817f8c471b6a3f31',
    messagingSenderId: '476508855204',
    projectId: 'notes-michu',
    authDomain: 'notes-michu.firebaseapp.com',
    storageBucket: 'notes-michu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA12NcjZE_uks7ALbAp41LlsvUefEv8cYw',
    appId: '1:476508855204:android:742786313e4fd3fc6a3f31',
    messagingSenderId: '476508855204',
    projectId: 'notes-michu',
    storageBucket: 'notes-michu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcX6KxvAD1VxxajIHelljfH-tBYji3has',
    appId: '1:476508855204:ios:65a5354364cb4a596a3f31',
    messagingSenderId: '476508855204',
    projectId: 'notes-michu',
    storageBucket: 'notes-michu.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcX6KxvAD1VxxajIHelljfH-tBYji3has',
    appId: '1:476508855204:ios:65a5354364cb4a596a3f31',
    messagingSenderId: '476508855204',
    projectId: 'notes-michu',
    storageBucket: 'notes-michu.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANAzvls5G_xdVx5LPxB7BKqsbjyl78SMA',
    appId: '1:476508855204:web:8fdf6f21962c1f076a3f31',
    messagingSenderId: '476508855204',
    projectId: 'notes-michu',
    authDomain: 'notes-michu.firebaseapp.com',
    storageBucket: 'notes-michu.firebasestorage.app',
  );

}