// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa6skVUZjNLSJFaKliaMY42B5v475LLtM',
    appId: '1:398065094684:web:84749849810b0315bb0fd9',
    messagingSenderId: '398065094684',
    projectId: 'cepu-firebase-michu',
    authDomain: 'cepu-firebase-michu.firebaseapp.com',
    storageBucket: 'cepu-firebase-michu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdVGXWdF8PisRQE4wQlCfn1V7egj7YZc',
    appId: '1:398065094684:android:e3db2d971a757a00bb0fd9',
    messagingSenderId: '398065094684',
    projectId: 'cepu-firebase-michu',
    storageBucket: 'cepu-firebase-michu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_vFESNNrvhuboQpoavgeHmwYyrbaqj0',
    appId: '1:398065094684:ios:1ef12f78cdcce9fbbb0fd9',
    messagingSenderId: '398065094684',
    projectId: 'cepu-firebase-michu',
    storageBucket: 'cepu-firebase-michu.firebasestorage.app',
    iosClientId: '398065094684-om5ltemrsrl6l8k6ns3bv62lh3cndifn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ_vFESNNrvhuboQpoavgeHmwYyrbaqj0',
    appId: '1:398065094684:ios:1ef12f78cdcce9fbbb0fd9',
    messagingSenderId: '398065094684',
    projectId: 'cepu-firebase-michu',
    storageBucket: 'cepu-firebase-michu.firebasestorage.app',
    iosClientId: '398065094684-om5ltemrsrl6l8k6ns3bv62lh3cndifn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa6skVUZjNLSJFaKliaMY42B5v475LLtM',
    appId: '1:398065094684:web:6abb396dd4a0f910bb0fd9',
    messagingSenderId: '398065094684',
    projectId: 'cepu-firebase-michu',
    authDomain: 'cepu-firebase-michu.firebaseapp.com',
    storageBucket: 'cepu-firebase-michu.firebasestorage.app',
  );

}