// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGdyt5EZi9CyeqzGi3PVrV7HKVLV3MSo',
    appId: '1:169727934708:web:7ea3aec65e26c0722cdea1',
    messagingSenderId: '169727934708',
    projectId: 'lat-uts-michu',
    authDomain: 'lat-uts-michu.firebaseapp.com',
    storageBucket: 'lat-uts-michu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ1x9pm3rgmPtchQYdFjMEIjSQqRyzER8',
    appId: '1:169727934708:android:0cb66dfb6d3fe2462cdea1',
    messagingSenderId: '169727934708',
    projectId: 'lat-uts-michu',
    storageBucket: 'lat-uts-michu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GAkBo7rZV3Ft-mTYmR7oyjK_8BYT9ZQ',
    appId: '1:169727934708:ios:bc8738cd7abf441b2cdea1',
    messagingSenderId: '169727934708',
    projectId: 'lat-uts-michu',
    storageBucket: 'lat-uts-michu.firebasestorage.app',
    iosBundleId: 'com.example.latUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4GAkBo7rZV3Ft-mTYmR7oyjK_8BYT9ZQ',
    appId: '1:169727934708:ios:bc8738cd7abf441b2cdea1',
    messagingSenderId: '169727934708',
    projectId: 'lat-uts-michu',
    storageBucket: 'lat-uts-michu.firebasestorage.app',
    iosBundleId: 'com.example.latUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMGdyt5EZi9CyeqzGi3PVrV7HKVLV3MSo',
    appId: '1:169727934708:web:22ff1b86e224b6522cdea1',
    messagingSenderId: '169727934708',
    projectId: 'lat-uts-michu',
    authDomain: 'lat-uts-michu.firebaseapp.com',
    storageBucket: 'lat-uts-michu.firebasestorage.app',
  );
}
