// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ei7_m4x18YEIHV-Pmmp8UwC-ezpsQ4c',
    appId: '1:691161442784:web:6ad8955220d1808fa06385',
    messagingSenderId: '691161442784',
    projectId: 'flutter-firebase-michhu12',
    authDomain: 'flutter-firebase-michhu12.firebaseapp.com',
    storageBucket: 'flutter-firebase-michhu12.firebasestorage.app',
    measurementId: 'G-6Q68GHT0BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJt5OX_XsQytr9kdUw7O04C4baEXvcWyE',
    appId: '1:691161442784:android:f5690c3a8b045693a06385',
    messagingSenderId: '691161442784',
    projectId: 'flutter-firebase-michhu12',
    storageBucket: 'flutter-firebase-michhu12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96GMX-nxNXBY28J9zc40TdhDmd3qJwKg',
    appId: '1:691161442784:ios:b73603d473773d92a06385',
    messagingSenderId: '691161442784',
    projectId: 'flutter-firebase-michhu12',
    storageBucket: 'flutter-firebase-michhu12.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96GMX-nxNXBY28J9zc40TdhDmd3qJwKg',
    appId: '1:691161442784:ios:b73603d473773d92a06385',
    messagingSenderId: '691161442784',
    projectId: 'flutter-firebase-michhu12',
    storageBucket: 'flutter-firebase-michhu12.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Ei7_m4x18YEIHV-Pmmp8UwC-ezpsQ4c',
    appId: '1:691161442784:web:9343b318d6cce682a06385',
    messagingSenderId: '691161442784',
    projectId: 'flutter-firebase-michhu12',
    authDomain: 'flutter-firebase-michhu12.firebaseapp.com',
    storageBucket: 'flutter-firebase-michhu12.firebasestorage.app',
    measurementId: 'G-KL5PL5WQDZ',
  );
}
